apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "local-path-provisioner.fullname" . }}
  namespace: {{ include "local-path-provisioner.namespace" . }}
  labels:
{{ include "local-path-provisioner.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.localPathProvisioner.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "local-path-provisioner.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      {{- with .Values.localPathProvisioner.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
{{ include "local-path-provisioner.labels" . | indent 8 }}
    spec:
    {{- with .Values.localPathProvisioner.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ template "local-path-provisioner.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.localPathProvisioner.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.localPathProvisioner.securityContext | nindent 12 }}
        {{- if .Values.localPathProvisioner.privateRegistry.registryUrl }}
          image: "{{ .Values.localPathProvisioner.privateRegistry.registryUrl }}/{{ .Values.localPathProvisioner.image.repository }}:{{ .Values.localPathProvisioner.image.tag }}"
        {{- else }}
          image: "{{ .Values.localPathProvisioner.image.repository }}:{{ .Values.localPathProvisioner.image.tag }}"
        {{- end }}
          imagePullPolicy: {{ .Values.localPathProvisioner.image.pullPolicy }}
          command:
            - local-path-provisioner
            - --debug
            - start
            - --config
            - /etc/config/config.json
            - --service-account-name
            - {{ template "local-path-provisioner.serviceAccountName" . }}
            - --provisioner-name
            - {{ template "local-path-provisioner.provisionerName" . }}
            - --helper-image
          {{- if .Values.localPathProvisioner.privateRegistry.registryUrl }}
            - "{{ .Values.localPathProvisioner.privateRegistry.registryUrl }}/{{ .Values.localPathProvisioner.helperImage.repository }}:{{ .Values.localPathProvisioner.helperImage.tag }}"
          {{- else }}
            - "{{ .Values.localPathProvisioner.helperImage.repository }}:{{ .Values.localPathProvisioner.helperImage.tag }}"
          {{- end }}
            - --configmap-name
            - {{ .Values.localPathProvisioner.configmap.name }}
          {{- if .Values.localPathProvisioner.workerThreads }}
            - --worker-threads
            - {{ .Values.localPathProvisioner.workerThreads | quote }}
          {{- end }}
          {{- if .Values.localPathProvisioner.provisioningRetryCount }}
            - --provisioning-retry-count
            - {{ .Values.localPathProvisioner.provisioningRetryCount | quote }}
          {{- end }}
          {{- if .Values.localPathProvisioner.deletionRetryCount }}
            - --deletion-retry-count
            - {{ .Values.localPathProvisioner.deletionRetryCount | quote }}
          {{- end }}
          {{- range .Values.localPathProvisioner.extraArgs }}
            - {{ . }}
          {{- end }}
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config/
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: CONFIG_MOUNT_PATH
              value: /etc/config/
          resources:
            {{- toYaml .Values.localPathProvisioner.resources | nindent 12 }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ .Values.localPathProvisioner.configmap.name }}
      {{- with .Values.localPathProvisioner.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.localPathProvisioner.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.localPathProvisioner.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
