{{- if .Values.localPathProvisioner.defaultSettings.registrySecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.localPathProvisioner.defaultSettings.registrySecret }}
  namespace: {{ include "local-path-provisioner.namespace" . }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "local-path-provisioner.secret" . }}
{{- end }}
